#!/usr/bin/perl

use 5.014;
use warnings;

use FindBin;
use lib "$FindBin::Bin/lib";

use WSL::Util;
use WSL::PathConverter;

our $EXPLORER_PATH = "/mnt/c/Windows/explorer.exe";

die "Can't find explorer at $EXPLORER_PATH" unless -e $EXPLORER_PATH;

for my $path (map { WSL::PathConverter::convertToWin($_) } WSL::Util::getInput()) {
	my $pid = fork();

	unless ($pid) {
		exec("/mnt/c/Windows/explorer.exe", $path);
		die "Exec failed: $!";
	}

	die "Can't fork" unless defined $pid;
}
