#!/usr/bin/perl

use 5.014;
use warnings;

use FindBin;
use lib "$FindBin::Bin/lib";

use WSL::Util;
use WSL::PathConverter;

say for map { WSL::PathConverter::convertToWin($_) } WSL::Util::getInput();
